### ISSUE TITLE
write some docs

### ISSUE THREAD

**Issue by aschweigert** [INN/storytelling-tools#2]
It's not really super clear how this plugin works...some docs would probably be helpful.

**Comment by benlk** [comment]
There's minimal docs at https://labs.inn.org/2017/07/13/storytelling-tools-plugin-for-wordpress/, but we do need real docs.

**Comment by benlk** [comment]
The readme.txt and readme.md files have more-thorough docs now: https://wordpress.org/plugins/storytelling-tools/

I'm going to close this in favor of more-specific tickets.
